### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by smtaylor88** [chrisdannen/Introducing-Ethereum-and-Solidity#5]
Compiler error!  The keyword "emit" is needed to precede the "Transfer..." event.

**Comment by chrisdannen** [comment]
Thank you Steve! I've added the emit keyword before the Transfer function. I will compile and test later today to be sure it works.

**Comment by smtaylor88** [comment]
Excellent!  Glad to see you’re keeping it fresh.  You might do the same for the OWNED contract as well.

Sent from Mail for Windows 10

**Comment by chrisdannen** [comment]
Good idea, will do. By the way, I just released a new book with more contracts, if you're looking to level up. The "official" Github repo with the book projects will be available in about two weeks. Here's the book link for now, but you don't need to buy it; the projects will be free and open:  

https://www.amazon.com/Building-Games-Ethereum-Smart-Contracts/dp/148423491X/ref=as_li_ss_tl?ie=UTF8&qid=1527460095&sr=8-1&keywords=ethereum+games&linkCode=sl1&tag=supertemp30-20&linkId=97d89ddf97d26cb8d67bb902d6cc9b70
