### ISSUE TITLE
Defining constructors as functions  is deprecated

### ISSUE THREAD

**Issue by IgorStojanov** [chrisdannen/Introducing-Ethereum-and-Solidity#6]
Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead.

Instead of function MyToken(args) use constructor(args)

**Comment by Soros777** [comment]
I copied the contract code from the site https://github.com/chrisdannen/Introducing-Ethereum-and-Solidity/blob/master/mytoken.sol
Pasted the code into the browser Mist. The browser gave an error: "Defining constructors as functions with the same name as the contract is deprecated".
![2018-10-07 14 33 35](https://user-images.githubusercontent.com/43518259/46583350-5402b400-ca5e-11e8-9f43-a032e0752880.png)

**Comment by chrisdannen** [comment]
Renamed function "constructor."
