### ISSUE TITLE
Owned contract can't complied

### ISSUE THREAD

**Issue by bartkim0426** [chrisdannen/Introducing-Ethereum-and-Solidity#7]
Owned contract exmple in chapter 5 can't compiled.

**Comment by praneethvallabha** [comment]
Creating Own contract Example in chapter 5 can't complied.
![caputer2](https://user-images.githubusercontent.com/44611528/52599573-4ec4d400-2e59-11e9-8f43-744c986d0e5e.JPG)

**Comment by chrisdannen** [comment]
Unfortunately the RPC methods for contract compilation were [removed](https://github.com/ethereum/mist/issues/3366) from Parity and Geth in 2017. This screenshot shows the use of wallet.ethereum.org, which relies on `curl` to compile contracts. 

For simplicity, I am updating this contract to use the same sample token contract as the Homestead [documentation](https://ethereum.org/token#the-code).

By the way, this is MyToken.sol, not Owned.sol.
